import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BarChart3, Bike, BookOpen, Database, Download, UploadCloud, Users} from 'lucide-react';
import './styles.css';

const api = async (path, body) => {
  const res = await fetch(path, {method: body ? 'POST' : 'GET', headers: {'Content-Type': 'application/json'}, body: body ? JSON.stringify(body) : undefined});
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error(data.error || 'request failed');
  return data;
};

function App(){
  const [user,setUser]=useState(null); const [view,setView]=useState('landing'); const [msg,setMsg]=useState('');
  useEffect(()=>{api('/api/auth/me').then(d=>{setUser(d.user); setView('dashboard')}).catch(()=>{})},[]);
  const authed = (u)=>{setUser(u); setView('dashboard'); setMsg('')};
  return <>
    <header className="topbar"><div className="brand"><span>PSCPT</span><small>PS Correlation Platform</small></div><nav>{user?<><button onClick={()=>setView('dashboard')}>Dashboard</button><button onClick={()=>setView('uploads')}>Sources</button><button onClick={()=>setView('psmonth')}>PS-Month</button><button onClick={()=>setView('analysis')}>Analysis</button><button onClick={()=>setView('guide')}>Guide</button><button onClick={()=>setView('change')}>Change Password</button><button onClick={async()=>{await api('/api/auth/logout',{});setUser(null);setView('landing')}}>Logout</button></>:<><button onClick={()=>setView('landing')}>Home</button><button onClick={()=>setView('login')}>Login</button><button className="solid" onClick={()=>setView('register')}>Register</button></>}</nav></header>
    {msg && <div className="toast">{msg}</div>}
    {view==='landing' && <Landing go={setView}/>} {view==='login' && <Auth mode="login" done={authed}/>} {view==='register' && <Auth mode="register" done={authed}/>} {view==='forgot' && <Forgot setMsg={setMsg}/>} {view==='change' && <Change setMsg={setMsg}/>} {view==='dashboard' && <Dashboard user={user}/>} {view==='uploads' && <Uploads/>} {view==='psmonth' && <PSMonth/>} {view==='analysis' && <Analysis/>} {view==='guide' && <Guide/>}
    {(view==='login'||view==='register') && <p className="switch">Forgot password? <button onClick={()=>setView('forgot')}>Reset here</button></p>}
  </>;
}
function Landing({go}){return <main className="hero"><section><p className="eyebrow">offline-ready internal analytics</p><h1>Understand PS performance from factors, capability, and sales.</h1><p className="lead">PSCPT builds PS-month correlation reports from manual Excel uploads for Individual Factor, Individual Capability, and Sales Performance.</p><div className="actions"><button className="solid big" onClick={()=>go('register')}>Start Workspace</button><button className="ghost big" onClick={()=>go('login')}>Login</button></div></section><section className="grid">{[[Users,'Individual Factor','Profile, background, and distance'],[Database,'Individual Capability','Discipline, leads, learning, tenure, complaint'],[Bike,'Sales Performance','SO consistency, conversion, and product mix'],[BarChart3,'Correlation Engine','Pearson, Spearman, driver analysis'],[UploadCloud,'Upload Center','Validate columns, periods, and PS match'],[BookOpen,'User Guide','Flow, source replacement, and seed files']].map(([Icon,t,d])=><article className="card" key={t}><Icon/><h3>{t}</h3><p>{d}</p></article>)}</section></main>}
function Auth({mode,done}){const [f,setF]=useState({name:'',email:'',password:''}); const [err,setErr]=useState(''); const submit=async e=>{e.preventDefault();setErr('');try{const d=await api(`/api/auth/${mode}`,f);done(d.user)}catch(x){setErr(x.message)}};return <Form title={mode==='login'?'Welcome back':'Create PSCPT account'} onSubmit={submit} err={err}>{mode==='register'&&<input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input placeholder="Email" type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input placeholder="Password min 8 chars" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><button className="solid">{mode==='login'?'Login':'Register'}</button></Form>}
function Forgot({setMsg}){const [email,setEmail]=useState(''); const [link,setLink]=useState('');return <Form title="Forgot password" onSubmit={async e=>{e.preventDefault();const d=await api('/api/auth/forgot-password',{email});setLink(d.reset_link||'');setMsg('Reset link generated for local dev')}}><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><button className="solid">Generate Reset Link</button>{link&&<code className="resetlink">{link}</code>}</Form>}
function Change({setMsg}){const [f,setF]=useState({currentPassword:'',newPassword:''});return <Form title="Change password" onSubmit={async e=>{e.preventDefault();await api('/api/auth/change-password',f);setMsg('Password changed')}}><input type="password" placeholder="Current password" onChange={e=>setF({...f,currentPassword:e.target.value})}/><input type="password" placeholder="New password min 8 chars" onChange={e=>setF({...f,newPassword:e.target.value})}/><button className="solid">Change Password</button></Form>}
function Form({title,onSubmit,children,err}){return <main className="auth"><form onSubmit={onSubmit}><h2>{title}</h2>{children}{err&&<p className="error">{err}</p>}</form></main>}



function Analysis(){
  const [snapshots,setSnapshots]=useState([]); const [snapshotID,setSnapshotID]=useState(''); const [target,setTarget]=useState('so_total_month'); const [features,setFeatures]=useState('learning_ability_avg_course_score,learning_will_score,tenure_alva_months,discipline_on_time_attendance_percent,conversion_leads_to_so_percent'); const [method,setMethod]=useState('pearson'); const [results,setResults]=useState([]); const [err,setErr]=useState('');
  useEffect(()=>{api('/api/ps-month/snapshots').then(d=>{setSnapshots(d.snapshots||[]); if(d.snapshots?.[0]) setSnapshotID(String(d.snapshots[0].id))})},[]);
  const run=async e=>{e.preventDefault();setErr('');try{const d=await api('/api/analysis/correlation',{snapshot_id:Number(snapshotID),target,features:features.split(',').map(x=>x.trim()).filter(Boolean),method});setResults(d.results||[])}catch(x){setErr(x.message)}};
  return <main className="dash"><h1>Correlation Engine</h1><p>Pearson/Spearman awal. Angka ini asosiasi, bukan bukti sebab-akibat.</p><form className="analysisbox" onSubmit={run}><select value={snapshotID} onChange={e=>setSnapshotID(e.target.value)}>{snapshots.map(s=><option key={s.id} value={s.id}>{s.period} ({s.row_count} rows)</option>)}</select><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="target metric"/><input value={features} onChange={e=>setFeatures(e.target.value)} placeholder="feature metrics comma separated"/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="pearson">Pearson</option><option value="spearman">Spearman</option></select><button className="solid">Run Correlation</button>{err&&<p className="error">{err}</p>}</form><section className="panel"><h2>Results</h2>{results.length===0?<p>No result yet.</p>:<table><thead><tr><th>Feature</th><th>Target</th><th>Corr</th><th>Strength</th><th>N</th><th>Missing</th></tr></thead><tbody>{results.map(r=><tr key={r.feature}><td>{r.feature}</td><td>{r.target}</td><td>{r.correlation}</td><td>{r.direction} / {r.strength}</td><td>{r.sample_size}</td><td>{r.missing_pairs}</td></tr>)}</tbody></table>}</section></main>
}

function PSMonth(){
  const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)); const [items,setItems]=useState([]); const [msg,setMsg]=useState('');
  const load=()=>api('/api/ps-month/snapshots').then(d=>setItems(d.snapshots||[]));
  useEffect(()=>{load()},[]);
  const create=async e=>{e.preventDefault();setMsg('');const d=await api('/api/ps-month/snapshots/create',{period});const s=d.sources||{};setMsg(`Master ${period}: ${d.row_count||0} PS rows | factor ${s.individual_factor||0}, capability ${s.individual_capability||0}, sales ${s.sales_performance||0}`);load()};
  return <main className="dash"><h1>PS-Month Master</h1><p>1 row = 1 Product Specialist dalam 1 bulan. Ini pondasi korelasi.</p><form className="uploadbox" onSubmit={create}><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/><button className="solid">Build Master</button></form>{msg&&<p className="toastline">{msg}</p>}<section className="panel"><h2>Snapshots</h2>{items.length===0?<p>No snapshots yet.</p>:<table><thead><tr><th>Period</th><th>Status</th><th>Rows</th><th>Created</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.period}</td><td>{x.status}</td><td>{x.row_count}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table>}</section><section className="panel"><h2>Column Groups</h2><p>Keys, individual factor, individual capability, sales performance, controls, metrics JSON.</p></section></main>
}

function Uploads(){
  const [type,setType]=useState('individual_factor'); const [file,setFile]=useState(null); const [salesFile,setSalesFile]=useState(null); const [period,setPeriod]=useState(new Date().toISOString().slice(0,7)); const [result,setResult]=useState(null); const [items,setItems]=useState([]); const [runs,setRuns]=useState([]); const [err,setErr]=useState('');
  const load=()=>{api('/api/uploads/manual/list').then(d=>setItems(d.uploads||[])).catch(()=>{});api('/api/sources/runs').then(d=>setRuns(d.runs||[])).catch(()=>{})};
  useEffect(load,[]);
  const submit=async e=>{e.preventDefault();setErr('');setResult(null);if(!file){setErr('Choose .xlsx file');return} const fd=new FormData();fd.append('type',type);fd.append('file',file);try{const res=await fetch('/api/uploads/manual',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'upload failed');setResult(data);load()}catch(x){setErr(x.message)}};
  const uploadSales=async e=>{e.preventDefault();setErr('');setResult(null);if(!salesFile){setErr('Choose sales .xlsx file');return} const fd=new FormData();fd.append('period',period);fd.append('file',salesFile);try{const res=await fetch('/api/sources/sales/upload',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'sales upload failed');setResult(data);load()}catch(x){setErr(x.message)}};
  const syncSales=async()=>{setErr('');setResult(null);try{const data=await api('/api/sources/sales/sync',{period});setResult(data);load()}catch(x){setErr(x.message)}};
  return <main className="dash"><h1>Source Intake</h1><p>Upload manual Excel untuk Individual Factor, Individual Capability, dan Sales Performance.</p><section className="sourcegrid"><form className="panel sourcepanel" onSubmit={submit}><h2>Manual PSCPT</h2><select value={type} onChange={e=>setType(e.target.value)}><option value="individual_factor">Individual Factor</option><option value="individual_capability">Individual Capability</option><option value="sales_performance">Sales Performance</option></select><input type="file" accept=".xlsx" onChange={e=>setFile(e.target.files?.[0])}/><button className="solid">Upload File</button></form><form className="panel sourcepanel" onSubmit={uploadSales}><h2>Emica Sales Order</h2><input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/><input type="file" accept=".xlsx" onChange={e=>setSalesFile(e.target.files?.[0])}/><div className="splitactions"><button className="solid">Upload File</button><button type="button" className="ghost" onClick={syncSales}>Sync API</button></div></form></section>{err&&<p className="error">{err}</p>}{result&&<section className="panel wide"><h2>Result: {result.mode||'upload'} {result.filename||''}</h2><p>{result.row_count} rows{result.columns?.length?'. Columns: '+result.columns.join(', '):''}</p><pre>{JSON.stringify(result.preview,null,2)}</pre></section>}<section className="panel wide"><h2>Source Runs</h2>{runs.length===0?<p>No source runs yet.</p>:<table><thead><tr><th>Source</th><th>Mode</th><th>Period</th><th>Rows</th><th>Created</th></tr></thead><tbody>{runs.map(x=><tr key={x.id}><td>{x.source_type}</td><td>{x.mode}</td><td>{x.period}</td><td>{x.row_count}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table>}</section><section className="panel wide"><h2>Recent Manual Uploads</h2>{items.length===0?<p>No uploads yet.</p>:<table><thead><tr><th>Type</th><th>File</th><th>Rows</th><th>Created</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.type}</td><td>{x.filename}</td><td>{x.row_count}</td><td>{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table>}</section></main>
}

function Guide(){
  const seeders=[
    ['Individual Factor','/seeders/pscpt_dummy_individual_factor_2026-09.xlsx','Profile PS, background, jarak, komunitas, dan score factor.'],
    ['Individual Capability','/seeders/pscpt_dummy_individual_capability_2026-09.xlsx','Discipline, leads, learning, tenure, complaint, dan employment status.'],
    ['Sales Performance','/seeders/pscpt_dummy_sales_performance_2026-09.xlsx','SO, conversion, consistency, achievement, dan product mix.'],
  ];
  return <main className="dash guide"><h1>User Guide</h1><p>Alur kerja PSCPT untuk upload source, build master PS-month, dan baca korelasi.</p><section className="guidegrid"><article className="panel guidepanel"><h2>Flow Utama</h2><ol><li>Masuk ke menu Sources.</li><li>Upload 3 source: Individual Factor, Individual Capability, dan Sales Performance.</li><li>Masuk ke PS-Month, pilih period, lalu Build Master.</li><li>Masuk ke Analysis, pilih snapshot period, target metric, feature metrics, lalu Run Correlation.</li></ol></article><article className="panel guidepanel"><h2>Ganti Data Source</h2><ol><li>Upload source baru di kategori yang sama.</li><li>Source lama tetap tercatat di Recent Manual Uploads sebagai history.</li><li>Build Master ulang untuk period yang sama.</li><li>Analysis akan membaca snapshot/master terbaru setelah Build Master.</li></ol></article><article className="panel guidepanel"><h2>Catatan Perhitungan</h2><ul><li><code>work_experience_education_score</code> dihitung sistem dari <code>work_experience</code> dan <code>education_background</code>.</li><li><code>product_mix_score</code> idealnya dihitung sistem dari mix unit per motor dan mapping grade A-E.</li><li>Korelasi rendah di dummy data belum berarti faktor bisnisnya tidak penting.</li></ul></article></section><section className="panel wide"><h2>Seeder / Dummy Files</h2><div className="downloadgrid">{seeders.map(([name,url,desc])=><a className="downloadcard" href={url} download key={url}><Download/><span><b>{name}</b><small>{desc}</small></span></a>)}</div></section><section className="panel wide"><h2>Kolom Kunci</h2><p>Pastikan setiap file punya key yang konsisten supaya merge master rapi: <code>period</code>, <code>ps_employee_id</code>, <code>ps_name</code>, <code>ps_email</code>, <code>aec</code>, dan <code>region</code>.</p></section></main>
}

function Dashboard({user}){const [summary,setSummary]=useState(null);useEffect(()=>{api('/api/dashboard/summary').then(setSummary)},[]);return <main className="dash"><h1>Dashboard Overview</h1><p>Halo {user?.name}. Engine siap untuk PS-month pipeline.</p><div className="metricrow">{(summary?.cards||[]).map(c=><article className={'metric '+c.tone} key={c.label}><b>{c.value}</b><span>{c.label}</span></article>)}</div><section className="panel"><h2>Pipeline V1</h2><ol><li>Upload Individual Factor Excel.</li><li>Upload Individual Capability Excel.</li><li>Upload Sales Performance Excel.</li><li>Build PS-month master table and run correlation.</li></ol></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
